#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
$application = new \Symfony\Component\Console\Application('First console app');
$application->add(new \DenDude\SumCommand());
$application->add(new \DenDude\DateConvertCommand());
$application->run();